package com.moviebrowser.di

import com.jakewharton.retrofit2.converter.kotlinx.serialization.asConverterFactory
import com.moviebrowser.BuildConfig
import com.moviebrowser.core.util.EndPoints
import com.moviebrowser.data.remote.api.MovieApi
import com.moviebrowser.data.remote.interceptor.AuthInterceptor
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import javax.inject.Singleton

/**
 * Hilt module responsible for providing
 * all network-related dependencies:
 * - OkHttpClient
 * - Moshi
 * - Retrofit
 * - MovieApi
 */
@Module
@InstallIn(SingletonComponent::class)
object NetworkModule {

    /**
     * Provides singleton OkHttpClient.
     *
     * Includes:
     * - AuthInterceptor for attaching headers
     * - Logging interceptor for debugging network calls
     */
    @Provides
    @Singleton
    fun provideOkHttpClient(
        authInterceptor: AuthInterceptor
    ): OkHttpClient {

        // Logs request & response bodies (useful for debugging)
        val logging = HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        }

        return OkHttpClient.Builder()
            .addInterceptor(authInterceptor) // Adds authentication headers
            .addInterceptor(logging)         // Logs network traffic
            .build()
    }

    /**
     * Provides Moshi instance for JSON parsing.
     *
     * KotlinJsonAdapterFactory enables proper Kotlin support.
     */
    @Provides
    @Singleton
    fun provideMoshi(): Moshi {
        return Moshi.Builder()
            .add(KotlinJsonAdapterFactory())
            .build()
    }

    /**
     * Provides Retrofit instance configured with:
     * - Base URL from BuildConfig
     * - OkHttpClient
     * - Moshi converter
     */
    @Provides
    @Singleton
    fun provideRetrofit(
        okHttpClient: OkHttpClient,
        moshi: Moshi
    ): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BuildConfig.BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
    }

    /**
     * Provides implementation of MovieApi
     * generated by Retrofit.
     */
    @Provides
    @Singleton
    fun provideMovieApi(
        retrofit: Retrofit
    ): MovieApi {
        return retrofit.create(MovieApi::class.java)
    }
}
